name: scrape

on:
  schedule:
    - cron: "*/5 * * * *" # runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      
      - name: Setup Go compiler
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      
