name: Trigger site rebuild

on:
  push
  # schedule:
    # - cron: '*/1 * * * *'

jobs:
  build:
    name: Trigger site rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://<webhook-endpoint-url>
